name: build-docker-image
on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
    branches:
      - dev

concurrency: 
  group: docker
env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}-build:latest

jobs:
  build-docker-image:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest  # Make sure to use a runner with Docker installed
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        name: checkout

      - id: build-docker-image
        name: Build and Publish docker image
        run: |
          make docker-image-build    # Build the Docker image
          make docker-image-push     # Push the image to GHCR
          make docker-image-pull     # Optional: Pull the image if needed
